booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'
urlpatterns = [
    #/booking/
    path('', views.index, name='index'),

    #/booking/con_indi/
    path('con_indi/', views.con_indi, name='con_indi'),

    #/booking/con_orga/
    path('con_orga/', views.con_orga, name='con_orga'),

    #/booking/list_indi/
    path('list_indi/', views.list_indi, name='list_indi'),

    #/booking/list_orga/
    path('list_orga/', views.list_orga, name='list_orga'),
]

project01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('booking/', include('booking.urls')),
]

booking/models.py
from django.db import models
from django.utils import timezone

class BookingListIndi(models.Model):
    name_person = models.CharField(max_length=200)
    industry_name = models.CharField(max_length=100)
    date_visit = models.DateField(default=timezone.now)
    slot_time = models.IntegerField(default=0)
    visiting_members = models.IntegerField(default=0)
    street_name = models.CharField(max_length=150)
    city_name = models.CharField(max_length=100)
    pin_code = models.CharField(max_length=10)
    code = models.CharField(max_length=20)
    visited = models.BooleanField(default=False)

class BookingListOrga (models.Model):
    name_person = models.CharField(max_length=200)
    organisation_name = models.CharField(max_length=200)
    industry_name = models.CharField(max_length=100)
    date_visit = models.DateField(default=timezone.now)
    slot_time = models.IntegerField(default=0)
    visiting_members = models.IntegerField(default=0)
    street_name = models.CharField(max_length=150)
    city_name = models.CharField(max_length=100)
    pin_code = models.CharField(max_length=10)
    code = models.CharField(max_length=20)
    visited = models.BooleanField(default=False)

booking/forms.py
from django import forms
from .models import BookingListIndi, BookingListOrga

class PostForm1(forms.ModelForm):
    class Meta:
        model = BookingListIndi
        exclude = ('code', 'visited')

class PostForm2(forms.ModelForm):
    class Meta:
        model = BookingListOrga
        exclude = ('code', 'visited')

booking/views.py
from django.shortcuts import render
from .models import BookingListIndi, BookingListOrga
from .forms import PostForm1, PostForm2
from django.http import HttpResponse

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage

import random
import string

def rand_str(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

# Create your views here.
def sending_email(site, user, current_site, code, to_email):
    mail_subject = 'Thanks for choosing our App'
    message = render_to_string(site, {
        'user': user,
        'domain': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'code': code,
    })
    email = EmailMessage(
        mail_subject, message, to=[to_email]
    )
    email.content_subtype = 'html'
    email.mixed_subtype = 'related'

    email.send()


def index(request):
    return render(request, 'booking/index.html')

def con_indi(request):
    if request.method == 'POST':
        form = PostForm1(request.POST)
        if form.is_valid():
            name_person = form.cleaned_data['name_person']
            industry_name = form.cleaned_data['industry_name']
            date_visit = form.cleaned_data['date_visit']
            slot_time = form.cleaned_data['slot_time']
            visiting_members = form.cleaned_data['visiting_members']
            street_name = form.cleaned_data['street_name']
            city_name = form.cleaned_data['city_name']
            pin_code = form.cleaned_data['pin_code']
            code = rand_str()
            p = BookingListIndi(name_person=name_person, industry_name=industry_name, date_visit=date_visit,
                                slot_time=slot_time, visiting_members=visiting_members, street_name=street_name,
                                city_name=city_name, pin_code=pin_code, code=code)
            p.save()

            user = form.save(commit=False)
            user.is_active = False
            current_site = get_current_site(request)
            to_email = 'lushaankkancherla1999@gmail.com'
            site = 'booking/ticket_gen_indi.html'
            sending_email(site, user, current_site, code, to_email)
            return render(request, 'booking/success.html')
        else:
            return HttpResponse("<h3>You didn't make it</h3>")
    else:
        form = PostForm1()
    return render(request, 'booking/book_indi.html', context={'form': form})

def con_orga(request):
    if request.method == 'POST':
        form = PostForm2(request.POST)
        if form.is_valid():
            name_person = form.cleaned_data['name_person']
            industry_name = form.cleaned_data['industry_name']
            organisation_name = form.cleaned_data['organisation_name']
            date_visit = form.cleaned_data['date_visit']
            slot_time = form.cleaned_data['slot_time']
            visiting_members = form.cleaned_data['visiting_members']
            street_name = form.cleaned_data['street_name']
            city_name = form.cleaned_data['city_name']
            pin_code = form.cleaned_data['pin_code']
            code = rand_str()
            p = BookingListOrga(name_person=name_person, industry_name=industry_name,
                                organisation_name=organisation_name, date_visit=date_visit, slot_time=slot_time,
                                visiting_members=visiting_members, street_name=street_name, city_name=city_name,
                                pin_code=pin_code, code=code)
            p.save()

            user = form.save(commit=False)
            user.is_active = False
            current_site = get_current_site(request)
            to_email = 'lushaankkancherla1999@gmail.com'
            site = 'booking/ticket_gen_orga.html'
            sending_email(site, user, current_site, code, to_email)
            return render(request, 'booking/success.html')
        else:
            return HttpResponse("<h3>You didn't make it</h3>")
    else:
        form = PostForm2()
    return render(request, 'booking/book_orga.html', context={'form': form})

def list_indi(request):
    all_lists = BookingListIndi.objects.all()
    return render(request, 'booking/list_indi.html', {'all_lists':all_lists})

def list_orga(request):
    all_lists = BookingListOrga.objects.all()
    return render(request, 'booking/list_orga.html', {'all_lists':all_lists})

booking/templates/booking/book_indi.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        body, html {
            height: 100%;
        }
        .p-lax{
            background-image:url('{{ static }}/../static/images/rdr2.png');
            height: 100%;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    </style>
</head>
<body>
    <div class="p-lax">
    </div>
    <div class="container width-50" style="width:40%" id="sec02">
    <b><h2> Please Fill out the form for Booking </h2></b><br>
    <form action="{% url 'booking:con_indi' %}" method="POST" >
        {% csrf_token %}
        <h4>{{ form|crispy }}</h4><br>
        <input type="submit" value="Book Now" class="btn btn-success pull-right">
    </form>
    </div>
</body>
</html>

booking/templates/booking/book_orga.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css'%}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        body, html {
            height: 100%;
        }
        .p-lax{
            background-image:url('{{ static }}/../static/images/rdr2.png');
            height: 100%;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    </style>
</head>
<body>
    <div class="p-lax">
    </div>
    <div class="container width-50" style="width:40%" id="sec02">
    <b><h2> Please Fill out the form for Booking </h2></b><br>
    <form action="{% url 'booking:con_orga' %}" method="POST" >
        {% csrf_token %}
        <h4>{{ form|crispy }}</h4><br>
        <input type="submit" value="Book Now" class="btn btn-success pull-right">
    </form>
    </div>
</body>
</html>

booking/templates/booking/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <div class="form-group width-70">
        <br><br>
        <a href="{% url 'booking:con_indi' %}"><button class="btn btn-primary">Individual Booking</button></a>
        <a href="{% url 'booking:con_orga' %}"><button class="btn btn-primary">Organisation Booking</button></a>
        <!-- <a href="../abc.html">Click Me For Fun</a> -->
        <br><br><br>
        <a href="{% url 'booking:list_indi' %}"><button class="btn btn-primary">Individuals List</button></a>
        <a href="{% url 'booking:list_orga' %}"><button class="btn btn-primary">Organisations List</button></a>
        <br><br>

    </div>
</body>
</html>

booking/templates/booking/list_indi.html
<!DOCTYPE html>
<html lang="en">
{% load admin_urls %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
{% if all_lists %}
    <h3>List of all Members Booked</h3>
    <table class="table-bordered">
        <tr>
            <th>Name of the Individual</th>&nbsp;
            <th>Industry Name</th>&nbsp;
            <th>Date of Visit</th>&nbsp;
            <th>Slot Booked</th>&nbsp;
            <th>Number of People Acccompanied</th>&nbsp;
            <th>Street Name</th>&nbsp;
            <th>City Name</th>&nbsp;
            <th>Pin/Zip Code</th>&nbsp;
            <th>Edit Booking</th>&nbsp;
            <th>Delete Record</th>
        </tr>
        {% for list in all_lists %}
        <tr>
            <td>{{ list.name_person }}</td>
            <td>{{ list.industry_name }}</td>
            <td>{{ list.date_visit }}</td>
            <td>{{ list.slots_present }}</td>
            <td>{{ list.visiting_members }}</td>
            <td>{{ list.street_name }}</td>
            <td>{{ list.city_name }}</td>
            <td>{{ list.pin_code }}</td>
            <td><button class="btn"><a href="{% url 'admin:booking_bookinglistindi_change' list.id %}">Changing</a></button></td>
            <td><button class="btn"><a href="{% url 'admin:booking_bookinglistindi_delete' list.id %}">Delete</a></button></td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <h3>You Don't any Members booked</h3>
{% endif %}
</body>
</html>

booking/templates/booking/list_orga.html
<!DOCTYPE html>
<html lang="en">
{% load admin_urls %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
{% if all_lists %}
    <h3>List of all Members Booked</h3>
    <table class="table-bordered">
        <tr>
            <th>Name of the Individual Booked</th>&nbsp;&nbsp;
            <th>Industry Name</th>&nbsp;&nbsp;
            <th>Organisation Name</th>&nbsp;
            <th>Date of Visit</th>&nbsp;&nbsp;
            <th>Slot Booked</th>
            <th>Number of People Acccompanied</th>
            <th>Street Name</th>&nbsp;&nbsp;
            <th>City Name</th>&nbsp;&nbsp;
            <th>Pin/Zip Code</th>&nbsp;
            <th>Edit Booking</th>&nbsp;
            <th>Delete Record</th>
        </tr>
        {% for list in all_lists %}
        <tr>
            <td>{{ list.name_person }}</td>
            <td>{{ list.industry_name }}</td>
            <td>{{ list.organisation_name }}</td>
            <td>{{ list.date_visit }}</td>
            <td>{{ list.slots_present }}</td>
            <td>{{ list.visiting_members }}</td>
            <td>{{ list.street_name }}</td>
            <td>{{ list.city_name }}</td>
            <td>{{ list.pin_code }}</td>
            <td><button class="btn"><a href="{% url 'admin:booking_bookinglistindi_change' list.id %}">Changing</a></button></td>
            <td><button class="btn"><a href="{% url 'admin:booking_bookinglistindi_delete' list.id %}">Delete</a></button></td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <h3>You Don't any Members booked</h3>
{% endif %}
</body>
</html>

booking/templates/booking/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <h3>Your booking is recorded, Thank you for using our App </h3>
    <h5><a href="..">Click here to go to mainpage</a></h5>
</body>
</html>

booking/templates/booking/ticket_gen_indi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        h2 {font-family: Terminal Dosis; font-size: 40px; font-weight: 400; line-height: 44px;}
        table, td {border: 1px double black; font-size: 40px; font-weight: 400;}
        table {border-collapse: collapse}
    </style>
</head>
<body >
    <div style='width:100%;' >
    <h2>Hi , {{ user.name_person }}</h2>

    <table align="center">
        <tr>
            <td>Industry Name</td>
            <td>{{ user.industry_name }}</td>
        </tr>
        <tr>
            <td>Date of Visit</td>
            <td>{{ user.date_visit }}</td>
        </tr>
        <tr>
            <td>Slot No</td>
            <td>{{ user.slot_time }}</td>
        </tr>
        <tr>
            <td>Number of People</td>
            <td>{{ user.visiting_members }}</td>
        </tr>
        <tr>
            <td>Code</td>
            <td>{{ code }}</td>
        </tr>
    </table>
    </div>
</body>
</html>

booking/templates/booking/ticket_gen_orga.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        h2 {font-family: Terminal Dosis; font-size: 40px; font-weight: 400; line-height: 44px;}
        table, td {border: 1px double black; font-size: 40px; font-weight: 400;}
        table {border-collapse: collapse}
    </style>
</head>
<body>
    Hi , {{ user.name_person }}
    <table>
        <tr>
            <td>Organisation Name</td>
            <td>{{ user.organisation_name }}</td>
        </tr>
        <tr>
            <td>Industry Name</td>
            <td>{{ user.industry_name }}</td>
        </tr>
        <tr>
            <td>Date of Visit</td>
            <td>{{ user.date_visit }}</td>
        </tr>
        <tr>
            <td>Slot No</td>
            <td>{{ user.slots_time }}</td>
        </tr>
        <tr>
            <td>Code</td>
            <td>{{ code }}</td>
        </tr>
    </table>
</body>
</html>